services:
  - type: cron
    name: avax-ema13-telegram
    runtime: python
    schedule: "1 * * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
